Lesson05 (Feature tests)
nikitoooid/qna pull request #3
Opened 2022-10-23 19:40 UTC by nikitoooid

2022-10-24 10:00 UTC, vkurennov requested changes

2022-10-24 10:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
форма создания овтета располагается на странице questions/show, поэтому отдельная страница new не нужна

2022-10-24 10:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path(@question), alert: 'Your answer not created!'
нельзя делать редирект, если есть ошибки валидации, так вся информация о них будет потеряна (и она из модели берется, а не из сообщения). нужно делать рендер страницы с формой, т.е. queastions/show, а на ней выводить уже ошибки валидации

2022-10-24 10:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user == current_user
1. так у тебя происходит лишний запрос на загрузку ассоциации user (а в видах еще и n+1 запрос). стоит сравнивать по user_id
2. такая проверка часто нужна будет, стоит вынести в метод `User#author_of?` и вызывать этот метод, где нужно. Ну и не забудь тесты модели на этот метод

2022-10-24 10:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render 'questions/show'
а вот здесь как раз можно было и редирект выполнить, впрочем, тут не критично, можно оставить как есть

2022-10-24 10:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body).merge(user_id: current_user.id)
не стоит мержить доп параметры здесь, тут задается лишь белый список того, что мы принимаем в запросе. лучше все остальное в явном виде устанавливать в экшенах/фильтрах

2022-10-24 10:00 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if question.user == current_user
замени на вызов `User#author_of?`

2022-10-24 10:00 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    = link_to('Delete answer', answer_path(answer), method: :delete) if answer.user == current_user
1. в видах не используй постфиксный if/unless - плохо читается
2. здесь как раз n+1 запрос (на каждую итерацию будет делаться еще и запрос на answer.user). если у тебя 10 ответов в коллекции, то будет 11 запросов выполнено: 1 на получение из базы коллекции и по еще одному на каждый ответ в коллекции. Сравнение по user_id решает эту проблему. Но лучше всего здесь использовать метод `User#author_of?` о котором я выше писал

2022-10-24 10:00 UTC, vkurennov commented on app/views/questions/show.html.slim
> += link_to('Delete question', question_path(question), method: :delete) if question.user == current_user
тут тоже использу префиксную форму if и замени проверку на вызов `User#author_of?`

2022-10-24 10:00 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
ну и где тесты? ))

2022-10-24 10:00 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
у тебя условие в контроллере, значит, надо все варианты тестировать. сделай 2 контекста - для автора и для не-автора

2022-10-24 11:15 UTC, nikitoooid commented on spec/controllers/answers_controller_spec.rb
> +  describe 'DELETE #destroy' do
:)

2022-10-25 07:49 UTC, vkurennov requested changes

2022-10-25 07:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  before_action :authenticate_user!, only: [:create]
а почему только на create? а destroy? вообще такие вещи лучше вешать на все и добавлять исключения через except

2022-10-25 07:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user && current_user.author_of?(@answer)
повесь фильтр authenticate_user! на этот экшн тоже, тогда не нужно будет двойное условие

2022-10-25 07:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:answer).permit(:body).merge(user_id: current_user.id)
[это](https://github.com/nikitoooid/qna/pull/3/files#r1003119189) нужно поправить

2022-10-25 07:49 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user && current_user.author_of?(@question)
здесь destroy защищен devise, поэтому составное условие не нужно, т.к. если управление дошло до сюда, current_user точно есть (это обеспечивает devise)

2022-10-25 07:49 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    - if current_user && current_user.author_of?(answer)
а вот здесь все правильно, т.к. вид может быть и для незалогиненного юзера, но чтобы все же избавиться от составного условия можно применить [safe navigation](https://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), тогда запись будет вида:

`if current_user&.author_of?(answer)`

2022-10-25 07:49 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user && current_user.author_of?(@question)
тут тоже стоит safe navigation использовать

2022-10-25 07:49 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
[это замечание не исправлено](https://github.com/nikitoooid/qna/pull/3/files#r1003122843)

2022-10-25 07:49 UTC, vkurennov commented on spec/feature/question/show_spec.rb
> +  given(:question) { create(:question, user_id: user.id) }
ассоциации не нужно по _id устанавливать (только сравнение по id имеет смысл), достаточно писать так `user: user`

2022-10-25 07:49 UTC, vkurennov commented on spec/feature/question/show_spec.rb
> +feature 'User can look at the question and its answers', %q{
в этой фиче надо проверить, что ответы отображаются на странице вопросов

2022-10-25 07:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(user.author_of? question).to be_truthy
есть более короткое и элегантное решение для тестирования предикатов, можно писать так:

`expect(user).to be_author_of(question)`

то есть вызов метода переносим после to/not_to, добавляем be_ к имени метода и убираем знак вопроса. если метод вернет true, проверка пройдет,  если false  - нет

2022-10-25 07:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +  it 'is expected to confirm its authorship over the question' do
при тестировании методов моделей, обычно принято такое оформление: для каждого метода свой describe с именем метода,  а внутри уже тесты, которые описывают возвращаемые значения в зависимости от условий (для сложных методов могут быть вложенные контексты еще). в данном случае это должно выглядеть так:


```
describe '#author_of?'  do # решетка - для инстанс методов, точка - для класс-методов
  it 'returns true if user is creator of the object' 
  it 'returns false if user is not creator of the object' 
end
```

2022-10-25 10:17 UTC, nikitoooid commented on spec/feature/question/show_spec.rb
> +feature 'User can look at the question and its answers', %q{
На 17 строке проверяется: `expect(page).to have_content answer.body`

2022-10-25 10:27 UTC, nikitoooid commented on spec/models/user_spec.rb
> +  it 'is expected to confirm its authorship over the question' do
А как тут правильнее делать? Если наш user может быть автором как вопроса, так и ответа - мы пишем тесты на проверку авторства для объектов каждого из этих классов? Или просто _if user is creator of the object_ и тестируем один из них?

Если второй вариант, то правильнее в один describe обернуть 4 теста или делать describe '#author_of? answer' и '#author_of? question' ?

2022-10-25 12:26 UTC, vkurennov approved these changes

2022-10-25 12:26 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      = link_to('Delete answer', answer_path(answer), method: :delete)
у хелепров в видах не принято скобки у методов ставить

2022-10-25 12:26 UTC, vkurennov commented on spec/feature/question/show_spec.rb
> +feature 'User can look at the question and its answers', %q{
да, но надо проверить **список** ответов, а не один. т.е. должна быть коллекция ответов

2022-10-25 12:26 UTC, vkurennov commented on spec/models/user_spec.rb
> +  it 'is expected to confirm its authorship over the question' do
Хороший вопрос, спасибо. Ответ на него такой: этот метод в принципе вообще не зависит от типа аргумента, а лишь от наличия у него атрибута user_id, соответственно, можно проверить на одном объекте (любом). можно было бы написать еще тест, предусматривающий поведение, если user_id нет. Но это имело бы смысл, если бы такое поведение было определено, ну например, мы бы хотели, чтобы в этом случае возвращался false. но т.к. такое поведение мы для метода не определяли, то лучше всего оставить поведение по-умолчанию, т.е. если передать объект в метод без user_id, то буде исключение, что и логично, т.к. позволит отследить факт, что где-то метод неверно вызывается.

2022-10-25 12:47 UTC, merged